apiVersion: v1
kind: Service
metadata:
  name: express
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: express
  sessionAffinity: None
  type: ClusterIP
