apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
spec:
  selector:
    matchLabels:
      run: express
  replicas: 8
  strategy: # not necessary
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: express
    spec:
      containers:
      - name: express
        image: a95818rw/expressdevopsday:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"  
      