apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
  ipFamilies:
  - IPv4
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    {{- include "template.labels" . | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
