apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      {{- include "template.labels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  {{- include "template.strategy" . | nindent 2 }}
  template:
    metadata:
      labels:
        {{- include "template.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
          protocol: TCP
        {{- include "template.livenessProbe" . | nindent 8 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
